export const GET_LOCATION = "GET_LOCATION";
export const OPEN_YOUR_JURIS ="OPEN_YOUR_JURIS";
export const OPEN_STATION_BOUNDS="OPEN_STATION_BOUNDS";
export const OPEN_INCIDENT_JURIS="OPEN_INCIDENT_JURIS";
export const OPEN_NEAREST_STATION="OPEN_NEAREST_STATION";
